-- Migration: 20251109003000_seed_stanford_alumni_user_profiles.sql
-- Seed 50 Stanford alumni as users and user_profiles (mapped to existing user_profiles schema)
-- Note: This migration inserts placeholder users (with generated password_hash) and
-- inserts into user_profiles using the available columns in the schema. Some original
-- fields (degree, linkedin_url) are not present in the schema and are omitted.

-- Insert users (explicit ids so user_profiles can reference them)
INSERT INTO users (id, email, password_hash, role)
VALUES
  (1,  'marissa.mayer@example.com', gen_random_uuid()::text, 'alumni'),
  (2,  'sundar.pichai@example.com', gen_random_uuid()::text, 'alumni'),
  (3,  'reid.hoffman@example.com', gen_random_uuid()::text, 'alumni'),
  (4,  'vint.cerf@example.com', gen_random_uuid()::text, 'alumni'),
  (5,  'jensen.huang@example.com', gen_random_uuid()::text, 'alumni'),
  (6,  'vinod.khosla@example.com', gen_random_uuid()::text, 'alumni'),
  (7,  'jerry.yang@example.com', gen_random_uuid()::text, 'alumni'),
  (8,  'brian.acton@example.com', gen_random_uuid()::text, 'alumni'),
  (9,  'feng.zhang@example.com', gen_random_uuid()::text, 'alumni'),
  (10, 'daphne.koller@example.com', gen_random_uuid()::text, 'alumni'),
  (11, 'kevin.systrom@example.com', gen_random_uuid()::text, 'alumni'),
  (12, 'stephany.yong@example.com', gen_random_uuid()::text, 'alumni'),
  (13, 'rachel.romer.carlson@example.com', gen_random_uuid()::text, 'alumni'),
  (14, 'andrej.karpathy@example.com', gen_random_uuid()::text, 'alumni'),
  (15, 'neal.mohan@example.com', gen_random_uuid()::text, 'alumni'),
  (16, 'mary.barra@example.com', gen_random_uuid()::text, 'alumni'),
  (17, 'sergey.brin@example.com', gen_random_uuid()::text, 'alumni'),
  (18, 'larry.page@example.com', gen_random_uuid()::text, 'alumni'),
  (19, 'vlad.tenev@example.com', gen_random_uuid()::text, 'alumni'),
  (20, 'baiju.bhatt@example.com', gen_random_uuid()::text, 'alumni'),
  (21, 'ann.miura-ko@example.com', gen_random_uuid()::text, 'alumni'),
  (22, 'steve.jurvetson@example.com', gen_random_uuid()::text, 'alumni'),
  (23, 'jeff.seibert@example.com', gen_random_uuid()::text, 'alumni'),
  (24, 'forrest.li@example.com', gen_random_uuid()::text, 'alumni'),
  (25, 'reed.hastings@example.com', gen_random_uuid()::text, 'alumni'),
  (26, 'mike.krieger@example.com', gen_random_uuid()::text, 'alumni'),
  (27, 'ruth.porat@example.com', gen_random_uuid()::text, 'alumni'),
  (28, 'peter.thiel@example.com', gen_random_uuid()::text, 'alumni'),
  (29, 'david.filo@example.com', gen_random_uuid()::text, 'alumni'),
  (30, 'thomas.kurian@example.com', gen_random_uuid()::text, 'alumni'),
  (31, 'ken.xie@example.com', gen_random_uuid()::text, 'alumni'),
  (32, 'bobby.murphy@example.com', gen_random_uuid()::text, 'alumni'),
  (33, 'kevin.weil@example.com', gen_random_uuid()::text, 'alumni'),
  (34, 'jb.straubel@example.com', gen_random_uuid()::text, 'alumni'),
  (35, 'tony.xu@example.com', gen_random_uuid()::text, 'alumni'),
  (36, 'alex.karp@example.com', gen_random_uuid()::text, 'alumni'),
  (37, 'jawed.karim@example.com', gen_random_uuid()::text, 'alumni'),
  (38, 'rachel.holt@example.com', gen_random_uuid()::text, 'alumni'),
  (39, 'theresia.gouw@example.com', gen_random_uuid()::text, 'alumni'),
  (40, 'sheel.tyle@example.com', gen_random_uuid()::text, 'alumni'),
  (41, 'david.velez@example.com', gen_random_uuid()::text, 'alumni'),
  (42, 'marcos.galperin@example.com', gen_random_uuid()::text, 'alumni'),
  (43, 'john.donahoe@example.com', gen_random_uuid()::text, 'alumni'),
  (44, 'omid.kordestani@example.com', gen_random_uuid()::text, 'alumni'),
  (45, 'mike.schroepfer@example.com', gen_random_uuid()::text, 'alumni'),
  (46, 'gideon.yu@example.com', gen_random_uuid()::text, 'alumni'),
  (47, 'justin.rosenstein@example.com', gen_random_uuid()::text, 'alumni'),
  (48, 'clara.shih@example.com', gen_random_uuid()::text, 'alumni'),
  (49, 'nirav.tolia@example.com', gen_random_uuid()::text, 'alumni'),
  (50, 'jess.lee@example.com', gen_random_uuid()::text, 'alumni')
ON CONFLICT (id) DO NOTHING;

-- Ensure sequence for users.id is up-to-date
SELECT setval(pg_get_serial_sequence('users','id'), COALESCE((SELECT MAX(id) FROM users), 1));

-- Insert corresponding user_profiles (mapping available fields)
INSERT INTO user_profiles (user_id, full_name, grad_year, current_title, current_company, headline)
VALUES
  (1,  'Marissa Mayer', 1997, 'Co-founder', 'Sunshine', 'Artificial intelligence'),
  (2,  'Sundar Pichai', 1995, 'Chief Executive Officer', 'Alphabet Inc.', 'Product innovation'),
  (3,  'Reid Hoffman', 1990, 'Co-founder & Chairman', 'Inflection AI', 'Artificial intelligence; Venture capital'),
  (4,  'Vint Cerf', 1965, 'VP & Chief Internet Evangelist', 'Google', 'Internet networking & policy'),
  (5,  'Jensen Huang', 1992, 'Founder & CEO', 'NVIDIA', 'Graphics computing; AI'),
  (6,  'Vinod Khosla', 1980, 'Founder & Partner', 'Khosla Ventures', 'Networking; Clean energy'),
  (7,  'Jerry Yang', 1990, 'Founding Partner', 'AME Cloud Ventures', 'Internet technology; Investments'),
  (8,  'Brian Acton', 1994, 'Executive Chairman', 'Signal Foundation', 'Secure messaging; Privacy'),
  (9,  'Feng Zhang', 2009, 'Co-founder & Board Member', 'Beam Therapeutics', 'Gene editing (CRISPR)'),
  (10, 'Daphne Koller', 1993, 'Founder & CEO', 'Insitro', 'Machine learning; Computational biology'),
  (11, 'Kevin Systrom', 2006, 'Co-founder & CEO', 'Artifact (Nokto, Inc.)', 'Social media; Mobile apps'),
  (12, 'Stephany Yong', 2016, 'Product Manager', 'Meta (Facebook)', 'User growth & engagement'),
  (13, 'Rachel Romer Carlson', 2015, 'Co-founder & CEO', 'Guild Education', 'Education technology'),
  (14, 'Andrej Karpathy', 2015, 'Founding Research Scientist', 'OpenAI', 'Deep learning; Computer vision'),
  (15, 'Neal Mohan', 1996, 'Chief Executive Officer', 'YouTube (Google)', 'Online video; Digital advertising'),
  (16, 'Mary Barra', 1990, 'Chair & CEO', 'General Motors', 'Automotive engineering; Leadership'),
  (17, 'Sergey Brin', 1995, 'Co-founder & Board Member', 'Google/Alphabet', 'Internet search; Philanthropy'),
  (18, 'Larry Page', 1998, 'Co-founder & Board Member', 'Google/Alphabet', 'Internet search; Innovation'),
  (19, 'Vlad Tenev', 2008, 'Co-founder & Co-CEO', 'Robinhood', 'Financial technology'),
  (20, 'Baiju Bhatt', 2008, 'Co-founder & Co-CEO', 'Robinhood', 'Financial technology'),
  (21, 'Ann Miura-Ko', 2008, 'Co-founding Partner', 'Floodgate', 'Cybersecurity; Startups'),
  (22, 'Steve Jurvetson', 1995, 'Co-founder & Partner', 'Future Ventures', 'Space tech; Venture investing'),
  (23, 'Jeff Seibert', 2008, 'Co-founder & CEO', 'Digits', 'Mobile analytics; Finance software'),
  (24, 'Forrest Li', 2006, 'Founder & CEO', 'Sea Limited', 'E-commerce; Gaming'),
  (25, 'Reed Hastings', 1988, 'Co-founder & Chairman', 'Netflix', 'Streaming media; Education philanthropy'),
  (26, 'Mike Krieger', 2008, 'Co-founder & former CTO', 'Instagram', 'Social media; Product design'),
  (27, 'Ruth Porat', 1979, 'Chief Financial Officer', 'Alphabet Inc.', 'Finance; Technology policy'),
  (28, 'Peter Thiel', 1989, 'Co-founder & Partner', 'Founders Fund', 'Entrepreneurship; Venture capital'),
  (29, 'David Filo', 1990, 'Co-founder & Board Member', 'Yahoo', 'Web portals; Philanthropy'),
  (30, 'Thomas Kurian', 1995, 'Chief Executive Officer', 'Google Cloud', 'Cloud computing; Enterprise software'),
  (31, 'Ken Xie', 1992, 'Founder & CEO', 'Fortinet', 'Cybersecurity'),
  (32, 'Bobby Murphy', 2010, 'Co-founder & CTO', 'Snap Inc.', 'Social media; Augmented reality'),
  (33, 'Kevin Weil', 2007, 'Chief Product Officer', 'OpenAI', 'Product strategy; Consumer AI'),
  (34, 'JB Straubel', 2000, 'Co-founder & CEO', 'Redwood Materials', 'Battery technology; Clean energy'),
  (35, 'Tony Xu', 2013, 'Co-founder & CEO', 'DoorDash', 'Logistics; On-demand delivery'),
  (36, 'Alex Karp', 1995, 'Co-founder & CEO', 'Palantir Technologies', 'Data analytics; Security'),
  (37, 'Jawed Karim', 2004, 'Co-founder', 'YouTube', 'Online video; Entrepreneurship'),
  (38, 'Rachel Holt', 2015, 'Co-founder & Managing Partner', 'Construct Capital', 'Venture capital; Mobility'),
  (39, 'Theresia Gouw', 1997, 'Founding Partner', 'Acrew Capital', 'Venture capital; Diversity in tech'),
  (40, 'Sheel Tyle', 2012, 'Founder & CEO', 'Amplo', 'Emerging markets; Venture investing'),
  (41, 'David Vélez', 2010, 'Founder & CEO', 'Nubank', 'Fintech; Financial inclusion'),
  (42, 'Marcos Galperín', 1999, 'Founder & CEO', 'MercadoLibre', 'E-commerce'),
  (43, 'John Donahoe', 1986, 'President & CEO', 'Nike, Inc.', 'E-commerce; Leadership'),
  (44, 'Omid Kordestani', 1991, 'SVP & Executive Chairman (former)', 'Google (formerly Twitter)', 'Internet business; Strategy'),
  (45, 'Mike Schroepfer', 1999, 'CTO (former)', 'Meta (Facebook)', 'Virtual reality; Climate tech'),
  (46, 'Gideon Yu', 1993, 'Chief Financial Officer (former)', 'Facebook / YouTube', 'Finance; Sports management'),
  (47, 'Justin Rosenstein', 2004, 'Co-founder & Board Director', 'Asana', 'Productivity software'),
  (48, 'Clara Shih', 2005, 'Co-founder & CEO', 'Hearsay Systems', 'Social media marketing'),
  (49, 'Nirav Tolia', 1994, 'Co-founder & former CEO', 'Nextdoor', 'Online communities'),
  (50, 'Jess Lee', 2001, 'Partner', 'Sequoia Capital', 'Consumer internet; Design')
ON CONFLICT (user_id) DO NOTHING;

-- End of migration
